### ISSUE TITLE
[Feature suggestion] GM background tint for notes not yet shared to players

### ISSUE THREAD

**Issue by mech-tools** [farling42/fvtt-revealed-notes-manager#2]
Hello,

The GM lacks a way to actually know what has been shared to players or not.

I suggest a (GM only) background tint setting for not yet shared notes, like this (reds are not yet shared):
![image](https://user-images.githubusercontent.com/1687854/187962827-98231edd-0dc2-4cbe-ae62-de259efeda7f.png)

Without it, all notes looks the same, and the GM has to double-click a note to know what its state is.

**Comment by farling42** [comment]
Add in V2.3

**Comment by mech-tools** [comment]
@farling42

As the GM the tint doesn't change when I change the state of a note from "not shared" to "shared".
I have a tint for not shared notes, but left the color field blank for shared notes.

**Comment by farling42** [comment]
I think it only really works if you set both. Since it permanently changes the note's icon tint to the value that you specify in the window.
There is no memory of the "original" icon tint from before the module started changing the icon tint.

**Comment by mech-tools** [comment]
@farling42 but it should set the tint back to "blank".

**Comment by farling42** [comment]
Ah, my intention was that a blank entry for this module would not affect the note's tint colour at all, rather than setting it back to blank.
I will have to work out a way of having a different option to enable/disable tinting if a blank entry is a valid icon tint setting.

**Comment by farling42** [comment]
V2.4 now only changes the icon tint temporarily, so the original value from the Note Configuration window will be used if the module's icon tint is left blank.

**Comment by mech-tools** [comment]
Great! Thx :)
